# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Specify used packages of CircleCI configuration.
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

# Repetitive commands through jobs.
commands:
  install_api:
    description: Install server-side dependencies
    steps:
      - run:
          name: Install udagram-api/
          command: npm run install:api

  install_frontend:
    description: Install client-side dependencies
    steps:
      - run:
          name: Install udagram-frontend/
          command: npm run install:frontend

# Define a job to be invoked later in a workflow.
jobs:
  # Install udagram-api/ dependencies job.
  install-api:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - node/install
      - checkout
      - install_api

  # Install udagram-frontend/ dependencies job.
  install-frontend:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - node/install
      - checkout
      - install_frontend

  # Build-Deploy job.
  build-deploy:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - checkout
      # install sub-jobs:
      - install_api
      - install_frontend

      # Build sub-jobs:
      - run:
          name: Build udagram-api/
          command: npm run build:api
      - run:
          name: Build udagram-frontend/
          command: npm run build:frontend

      # Deploy sub-jobs:
      - run:
          name: Deploy udagram-api/
          command: npm run deploy:api
      - run:
          name: Deploy udagram-frontend/
          command: npm run deploy:frontend

# Invoke jobs via workflows
workflows:
  project-workflow:
    jobs:
      - install-api
      - install-frontend
      - build-deploy:
          requires:
            - install-api
            - install-frontend
