# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Specify used packages of CircleCI configuration.
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

# Define a job to be invoked later in a workflow.
jobs:
  # Install-Build-Deploy job.
  install-build-deploy:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    steps:
      - node/install
      - aws-cli/setup
      - eb/setup
      - checkout

      # Install sub-jobs:
      - run:
          name: Install udagram-api/
          command: npm run install:api
      - run:
          name: Install udagram-frontend/
          command: npm run install:frontend

      # Build sub-jobs:
      - run:
          name: Build udagram-api/
          command: npm run build:api
      - run:
          name: Build udagram-frontend/
          command: npm run build:frontend

      # Deploy sub-jobs:
      - run:
          name: Deploy udagram-api/
          command: npm run deploy:api
      - run:
          name: Deploy udagram-frontend/
          command: npm run deploy:frontend

# Invoke jobs via workflows
workflows:
  project-workflow:
    jobs:
      - install-build-deploy
